name: Go

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version-file: go.mod

    - name: Download module dependencies
      env:
        GOPROXY: "https://proxy.golang.org"
      run: go mod download

    - name: Test
      run: go test -v -coverprofile=coverage.txt ./...

    - name: Upload Coverage
      uses: codecov/codecov-action@0b35c9ecc4f0529d0eb674914510c22f85b196b4 # v7.1.0
      with:
        disable_search: true
        fail_ci_if_error: true
        files: ./coverage.txt
        use_oidc: true
